### ISSUE TITLE
Insufficient permissions on activating "Run on Windows Startup" throws exception

### ISSUE THREAD

**Issue by ralfbergs** [LibreHardwareMonitor/LibreHardwareMonitor#1013]
I'm not an administrator on this machine (so LHM doesn't display very many useful things to me, but that's a different thing), and when I try to make LHM run on startup I get the below exception:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition)
   at LibreHardwareMonitor.UI.StartupManager.set_Startup(Boolean value)
   at LibreHardwareMonitor.UI.MainForm.<.ctor>b__35_5(Object <p0>, EventArgs <p1>)
   at LibreHardwareMonitor.UI.UserOption.set_Value(Boolean value)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************

LibreHardwareMonitor
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Users/<theUser>/AppData/Local/Programs/LibreHardwareMonitor/LibreHardwareMonitor.exe
----------------------------------------
LibreHardwareMonitorLib
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Users/<theUser>/AppData/Local/Programs/LibreHardwareMonitor/LibreHardwareMonitorLib.DLL
----------------------------------------

```

First, the exception should be caught, the user should be notified about the failure, and they should be told that they need admin rights to autostart it for all users.

Alternatively LHM could be changed to set it up for the local user only in this case, and let the user know about this limited setup.

**Comment by PhyxionNL** [comment]
That's odd, as LHM should request admin access:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitor/Resources/app.manifest#L10

Windows also shows that for me:
![image](https://user-images.githubusercontent.com/7643972/225575421-7c02fc07-0610-4742-a85e-2237849a9582.png)

**Comment by ralfbergs** [comment]
Probably due to the enterprise environment where I was running the tool. I don't have admin rights there.
