### ISSUE TITLE
HidSharp RegisterClass failed error when initializing Computer object

### ISSUE THREAD

**Issue by uiharuayako** [LibreHardwareMonitor/LibreHardwareMonitor#1034]
First of all, thank you so much for creating and sharing this amazing open source library. Your hard work and dedication are truly appreciated!

I am using the LibreHardwareMonitor library in a plugin for a game. When I first load the plugin, it works fine and I am able to retrieve hardware information using the Computer object from the library. However, after I uninstall the plugin (calling the Computer object's Close method) and then try to reload it, I get the following error:
``` css
2023-03-30 04:39:10.491 +08:00 [FTL] Unhandled exception on AppDomain
System.InvalidOperationException: HidSharp RegisterClass failed.
   at HidSharp.Platform.Windows.WinHidManager.Run(Action readyCallback)
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
I tried releasing the resources used by the library but that did not resolve the issue. However, when I replaced the HidSharp library used by the LibreHardwareMonitor library with HidSharpCore, the error went away.

I suspect that the issue may be related to the HidSharp library not releasing all resources properly?

Thank you.

**Comment by uiharuayako** [comment]
I'm using .net6.0 and LibreHardwareMonitor 0.9.1
