### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by stefxx** [LibreHardwareMonitor/LibreHardwareMonitor#1042]
My little VB.net program runs fine on multiple systems except one. It crashes with this error:

System.NullReferenceException: Object reference not set to an instance of an object.
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Ipmi.Update(StringBuilder stringBuilder)
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Ipmi..ctor(Manufacturer manufacturer)
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO..ctor(Motherboard motherboard)
at LibreHardwareMonitor.Hardware.Motherboard.Motherboard..ctor(SMBios smBios, ISettings settings)
at LibreHardwareMonitor.Hardware.Motherboard.MotherboardGroup..ctor(SMBios smbios, ISettings settings)
at LibreHardwareMonitor.Hardware.Computer.AddGroups()
at LibreHardwareMonitor.Hardware.Computer.Open()

Where should I start investigating? Any suggestions?

**Comment by stefxx** [comment]
The impacted system is a "Supermicro X11SCL-IF" with an "Intel Xeon E-2176G" processor.

**Comment by stefxx** [comment]
I've tried running the LibreHardwareMonitor program 0.9.2 and it doesn't even start on this system. It seems to die silently.

**Comment by PhyxionNL** [comment]
Please run LHM under a debugger and see what's null.

**Comment by doolbneerg** [comment]
I think this is the same as #1054.

**Comment by stefxx** [comment]
I can confirm this issue has been resolved.
