### ISSUE TITLE
Support for ARM64 

### ISSUE THREAD

**Issue by almodad** [LibreHardwareMonitor/LibreHardwareMonitor#1162]
Are there plans to support ARM? The following exception is thrown on Surface Pro X:
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at LibreHardwareMonitor.Hardware.Cpu.CpuId..ctor(Int32 group, Int32 thread, GroupAffinity affinity)
   at LibreHardwareMonitor.Hardware.Cpu.CpuId.Get(Int32 group, Int32 thread)
   at LibreHardwareMonitor.Hardware.Cpu.CpuGroup.GetProcessorThreads()
   at LibreHardwareMonitor.Hardware.Cpu.CpuGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()

**Comment by md2k** [comment]
@PhyxionNL  any chances it will resolved since #984 merged ?

**Comment by Taiizor** [comment]
> [@PhyxionNL](https://github.com/PhyxionNL) any chances it will resolved since [#984](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/984) merged ?

Honestly, I’m curious about this too, but I don’t have an ARM64 device to test it on.

**Comment by Taiizor** [comment]
Windows 11 ARM64 installed on macOS - 0.9.5-pre498:

```
An error occurred: External component has thrown an exception.
   at LibreHardwareMonitor.Hardware.Cpu.CpuId..ctor(Int32 group, Int32 thread, GroupAffinity affinity)
   at LibreHardwareMonitor.Hardware.Cpu.CpuId.Get(Int32 group, Int32 thread)
   at LibreHardwareMonitor.Hardware.Cpu.CpuGroup.GetProcessorThreads()
   at LibreHardwareMonitor.Hardware.Cpu.CpuGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at TEST.Program.Main(String[] args) in E:\MyProject\Sucrose\Pro\Private\Others\LibreHardwareMonitorLib\TEST\TEST\Program.cs:line 24
```
