### ISSUE TITLE
Unable to find an entry point named 'ADL2_New_QueryPMLogData_Get' in DLL 'atiadlxx.dll'.

### ISSUE THREAD

**Issue by Just-Ch33s3** [LibreHardwareMonitor/LibreHardwareMonitor#664]
Hi and thanks for reading!
I'm currrently expiriencing problems reading out (old) AMD/ATI GPU Core/Fan/Temp values in Win10 21H2, 
the same machine successfully reported back values on Win7x64Sp1
the latest Win10 driver for this particular model(s) seems to be from 2015, (recent win versions might handle PCIE expansions differently?)

Running the standard LHM / OHM applications to test, resulting both clients to crash.

the LHM (dll-Version: 0.8.9.0) full report only exports following values regarding that particular adapter;
```
AMD Display Library

Status: OK

Number of adapters: 8

AdapterIndex: 0
isActive: 0
AdapterName: AMD FirePro V4900 (FireGL V)
UDID: PCI_VEN_1002&DEV_6749&SUBSYS_2B061002&REV_00_4&180F020B&0&0010A
PNPString: PCI\VEN_1002&DEV_6749&SUBSYS_2B061002&REV_00\4&180F020B&0&0010
Present: 0
VendorID: 0x1002
BusNumber: 2
DeviceNumber: 0
FunctionNumber: 0
AdapterID: 0x0

System.EntryPointNotFoundException: Unable to find an entry point named 'ADL2_New_QueryPMLogData_Get' in DLL 'atiadlxx.dll'.
   at LibreHardwareMonitor.Interop.AtiAdlxx.ADL2_New_QueryPMLogData_Get(IntPtr context, Int32 adapterIndex, ADLPMLogDataOutput& aDLPMLogDataOutput)
   at LibreHardwareMonitor.Hardware.Gpu.AmdGpu.Update()
   at LibreHardwareMonitor.Hardware.Gpu.AmdGpu..ctor(ADLAdapterInfo adapterInfo, ISettings settings)
   at LibreHardwareMonitor.Hardware.Gpu.AmdGpuGroup..ctor(ISettings settings)
```
   
By running 'Get-CimInstance CIM_VideoController' inside Powershell i retrieve the following info, which might help in troubleshooting ?)
   
```
Caption                      : AMD FirePro V4900 (FireGL V)
Description                  : AMD FirePro V4900 (FireGL V)
InstallDate                  :
Name                         : AMD FirePro V4900 (FireGL V)
Status                       : OK
Availability                 : 3
ConfigManagerErrorCode       : 0
ConfigManagerUserConfig      : False
CreationClassName            : Win32_VideoController
DeviceID                     : VideoController2
ErrorCleared                 :
ErrorDescription             :
LastErrorCode                :
PNPDeviceID                  : PCI\VEN_1002&DEV_6749&SUBSYS_2B061002&REV_00\4&180F020B&0&0010
PowerManagementCapabilities  :
PowerManagementSupported     :
StatusInfo                   :
SystemCreationClassName      : Win32_ComputerSystem
SystemName                   : ******
MaxNumberControlled          :
ProtocolSupported            :
TimeOfLastReset              :
AcceleratorCapabilities      :
CapabilityDescriptions       :
CurrentBitsPerPixel          : 32
CurrentHorizontalResolution  : 1920
CurrentNumberOfColors        : 4294967296
CurrentNumberOfColumns       : 0
CurrentNumberOfRows          : 0
CurrentRefreshRate           : 60
CurrentScanMode              : 4
CurrentVerticalResolution    : 1200
MaxMemorySupported           :
MaxRefreshRate               : 60
MinRefreshRate               : 23
NumberOfVideoPages           :
VideoMemoryType              : 2
VideoProcessor               : AMD Radeon Graphics Processor (0x6749)
NumberOfColorPlanes          :
VideoArchitecture            : 5
VideoMode                    :
AdapterCompatibility         : Advanced Micro Devices, Inc.
AdapterDACType               : Internal DAC(400MHz)
AdapterRAM                   : 1073741824
ColorTableEntries            :
DeviceSpecificPens           :
DitherType                   : 0
DriverDate                   : 04/11/2015 01:00:00
DriverVersion                : 15.201.2401.0
ICMIntent                    :
ICMMethod                    :
InfFilename                  : oem10.inf
InfSection                   : ati2mtag_NIGL
InstalledDisplayDrivers      : aticfx64.dll,aticfx64.dll,aticfx64.dll,amdxc64.dll
Monochrome                   : False
ReservedSystemPaletteEntries :
SpecificationVersion         :
SystemPaletteEntries         :
VideoModeDescription         : 1920 x 1200 x 4294967296 colors
PSComputerName               :
```

**Comment by PhyxionNL** [comment]
This has already been fixed in the latest build. You can download these here:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions
