### ISSUE TITLE
Index out of Range issue in TreeViewAdv.cs after returning from sleep

### ISSUE THREAD

**Issue by Eno77** [LibreHardwareMonitor/LibreHardwareMonitor#688]
I use the latest build from 1. March (pre97):

The following Error is shown, but LHM runs normal after that.
I hope the Error Text gives a hint to the issue.

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: Index out of range
   bei Aga.Controls.Tree.TreeViewAdv.ClearNodesSize(TreeModelEventArgs e, TreeNodeAdv parent) in D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.cs:Zeile 1227.

**Comment by mindplay-dk** [comment]
I got a very similar error not after hibernation, but just after cold booting my computer this morning.

Here's the full stack trace:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Aga.Controls.Tree.TreeNodeAdv.get_NextNode() in D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeNodeAdv.cs:line 252
   at Aga.Controls.Tree.TreeNodeAdv.get_NextVisibleNode() in D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeNodeAdv.cs:line 281
   at Aga.Controls.Tree.TreeViewAdv.<get_VisibleNodes>d__256.MoveNext() in D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.Properties.cs:line 74
   at Aga.Controls.Tree.TreeViewAdv.CreateRowMap() in D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.cs:line 890
   at Aga.Controls.Tree.TreeViewAdv.UnsafeFullUpdate() in D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.cs:line 684
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LibreHardwareMonitor
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/LibreHardwareMonitor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Aga.Controls
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/Aga.Controls.DLL
----------------------------------------
LibreHardwareMonitorLib
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/LibreHardwareMonitorLib.DLL
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: 2.10.1.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/Microsoft.Win32.TaskScheduler.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
OxyPlot
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/OxyPlot.DLL
----------------------------------------
OxyPlot.WindowsForms
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/OxyPlot.WindowsForms.DLL
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
gnmv5vr4
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
HidSharp
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Program%20Files/Libre%20Hardware%20Monitor/HidSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by sintech** [comment]
I observe similar error while playing Death Stranding
```
System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: Index out of range
   в Aga.Controls.Tree.TreeViewAdv.ClearNodesSize(TreeModelEventArgs e, TreeNodeAdv parent) в D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.cs:строка 1227
```

**Comment by Z3r10** [comment]
Just for reference, I opened another issue for this (sorry for the duplicate): https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1506

On my machine it is random, and not related to sleep nor hibernation (i just got it this morning 1 minute after cold boot).

**Comment by klinki** [comment]
I'm also hitting this.

<details><summary>Details</summary>

```
Informace o vyvolání ladění JIT najdete na konci této zprávy,
nikoli v tomto dialogovém okně.

************** Text výjimky **************
System.ArgumentOutOfRangeException: Index je mimo rozsah. Index musí být nezáporný a musí být menší než velikost kolekce.
Název parametru: index
   v System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   v System.Collections.Generic.List`1.get_Item(Int32 index)
   v Aga.Controls.Tree.TreeNodeAdv.get_NextNode() v D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeNodeAdv.cs:řádek 252
   v Aga.Controls.Tree.TreeNodeAdv.get_NextVisibleNode() v D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeNodeAdv.cs:řádek 281
   v Aga.Controls.Tree.TreeViewAdv.<get_VisibleNodes>d__261.MoveNext() v D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.Properties.cs:řádek 74
   v Aga.Controls.Tree.TreeViewAdv.CreateRowMap() v D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.cs:řádek 900
   v Aga.Controls.Tree.TreeViewAdv.UnsafeFullUpdate() v D:\a\LibreHardwareMonitor\LibreHardwareMonitor\Aga.Controls\Tree\TreeViewAdv.cs:řádek 694
   v System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   v System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   v System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   v System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9290.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LibreHardwareMonitor
    Verze sestavení: 0.9.4.0
    Verze Win32: 0.9.4.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/LibreHardwareMonitor.exe
----------------------------------------
System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9256.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9282.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Aga.Controls
    Verze sestavení: 1.7.0.0
    Verze Win32: 1.7.0.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/Aga.Controls.DLL
----------------------------------------
LibreHardwareMonitorLib
    Verze sestavení: 0.9.4.0
    Verze Win32: 0.9.4.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/LibreHardwareMonitorLib.DLL
----------------------------------------
System.Core
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9277.0 built by: NET481REL1LAST_B
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Verze sestavení: 2.11.0.0
    Verze Win32: 2.11.0.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/Microsoft.Win32.TaskScheduler.DLL
----------------------------------------
System.Xml
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Management
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Configuration.Install
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
OxyPlot
    Verze sestavení: 2.2.0.0
    Verze Win32: 2.2.0.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/OxyPlot.DLL
----------------------------------------
OxyPlot.WindowsForms
    Verze sestavení: 2.2.0.0
    Verze Win32: 2.2.0.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/OxyPlot.WindowsForms.DLL
----------------------------------------
amjg5o2e
    Verze sestavení: 0.0.0.0
    Verze Win32: 4.8.9282.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
mscorlib.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
HidSharp
    Verze sestavení: 2.1.0.0
    Verze Win32: 2.1.0.0
    Základ kódu (CodeBase): file:///C:/Users/david/AppData/Local/Microsoft/WinGet/Packages/LibreHardwareMonitor.LibreHardwareMonitor_Microsoft.Winget.Source_8wekyb3d8bbwe/HidSharp.DLL
----------------------------------------
System.Windows.Forms.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9032.0 built by: NET481REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Ladění JIT **************
Aby bylo povoleno ladění JIT, musí konfigurační soubor
pro tuto aplikaci nebo počítač (machine.config) mít
v oddílu system.windows.forms nastavenou hodnotu njitDebugging.
Aplikace rovněž musí být kompilována s povoleným
laděním.

Příklad:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Je-li ladění JIT povoleno, budou všechny neošetřené výjimky
odeslány ladicímu programu JIT, který je registrován v počítači,
a nebudou zpracovány tímto dialogovým oknem.
```
</details>

**Comment by MayankJairaj** [comment]
For now I have just skipped the exception, will try and find some solution.

```
if (index < 0 || index >= parent.Nodes.Count)
{
continue;
}


```
