### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by MartinChrobak** [LibreHardwareMonitor/LibreHardwareMonitor#830]
When i try to start the app, it stops running after a short period. I can see running process in task manager for a second, but no window is opened.

**Comment by MySelections** [comment]
Me too.
Debug：
Application: LibreHardwareMonitor.exe
Framework version: v4.0.30319
Description:  The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.DateTime.DateToTicks(Int32, Int32, Int32)
   at LibreHardwareMonitor.Hardware.BiosInformation.GetDate(System.String)
   at LibreHardwareMonitor.Hardware.BiosInformation..ctor(Byte[], System.Collections.Generic.IList`1<System.String>)
   at LibreHardwareMonitor.Hardware.SMBios..ctor()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at LibreHardwareMonitor.UI.MainForm..ctor()
   at LibreHardwareMonitor.Program.Main()
