### ISSUE TITLE
Battery update negative of minimum value overflows

### ISSUE THREAD

**Issue by nickbabcock** [LibreHardwareMonitor/LibreHardwareMonitor#976]
There appears to be a battery condition that is causing a something like a [`MinValue`](https://learn.microsoft.com/en-us/dotnet/api/system.int32.minvalue?view=net-7.0), which can't be negated -- otherwise an exception is thrown.
```
System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at LibreHardwareMonitor.Hardware.Battery.Battery.Update()
   at OhmGraphite.UpdateVisitor.VisitHardware(IHardware hardware)
   at LibreHardwareMonitor.Hardware.Hardware.Accept(IVisitor visitor)
   at LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor)
   at OhmGraphite.UpdateVisitor.VisitComputer(IComputer computer)
   at LibreHardwareMonitor.Hardware.Computer.Accept(IVisitor visitor)
   at OhmGraphite.SensorCollector.ReadAllSensors()
   at OhmGraphite.PrometheusCollection.PollSensors()
   at OhmGraphite.LoggerUtils.LogAction(Logger logger, String msg, Action action)
```

I don't know what causes the issue. My best guess is this line:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/50f2d6073ca7c406e845611ca4c349394aa27ecc/LibreHardwareMonitorLib/Hardware/Battery/Battery.cs#L172

[As it's not possible](https://learn.microsoft.com/en-us/dotnet/api/system.math.abs?view=net-7.0#system-math-abs(system-int32)) to take the absolute of MinValue. If this is indeed the problem, it seems like the solution could be to first do the division and then take the absolute value.

I'm certainly happy to submit the change and see if this fixes the users problem

*Originally reported downstream at https://github.com/nickbabcock/OhmGraphite/issues/353*

**Comment by PhyxionNL** [comment]
Makes sense, thanks 👍
